---
language: "python"
python:
  - "3.6"

# Install python packages for ansible and linters.
install:
  - "pip install -r requirements.txt"

# Perform pre-checks
before_script:
  - "pylint *.py"

# Perform runbook testing with mock ASA inputs.
script:
  - "python test.py"
...
